version: '3'

volumes:
  datafiles:

services:
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  website:
    container_name: phpapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=employers
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
      - 8043:443
    depends_on:
      - mysql
